spring:
  flyway:
    enabled: false
    # locations:
    #   - classpath:db/migration/{vendor}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        id:
          "[new_generator_mappings]": false
        jdbc:
          "[time_zone]": UTC
