spring:
  security:
    user:
      password: ${SPRING_SECURITY_USER_PASSWORD}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    # open-in-view: false
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          "[new_generator_mappings]": false
        "[format_sql]": true
        jdbc:
          "[time_zone]": UTC
  threads:
    virtual:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui

application:
  security:
    jwt:
      issuer: ${APPLICATION_SECURITY_JWT_ISSUER}
      secret: ${APPLICATION_SECURITY_JWT_SECRET}
      validity-in-seconds: ${APPLICATION_SECURITY_JWT_VALIDITY_IN_SECONDS}
