spring:
  security:
    user:
      password: nmrony
  datasource:
    url: jdbc:mysql://mysqlserver5/spring_playground?useUnicode=yes&charset=utf8mb4&collation=utf8mb4_unicode_ci&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: nmrony
  jpa:
    # open-in-view: false
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        id:
          "[new_generator_mappings]": false
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true
        jdbc:
          "[time_zone]": UTC

springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui

application:
  security:
    jwt:
      issuer: secure.nmrony.info
      secret: zdtlD3JK56m6wTTgsNFhqzjqP
      validity-in-seconds: 604800