spring:
  security:
    user:
      password:
  datasource:
    url:
    username:
    password:
  jpa:
    # open-in-view: false
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        id:
          "[new_generator_mappings]": false
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true
        jdbc:
          "[time_zone]": UTC

springdoc:
  api-docs:
    enabled: true
    path: /rest-api-docs
  swagger-ui:
    path: /swagger-ui
