spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:file:/data/batch
    username: root
    password: nmrony
    driverClassName: org.h2.Driver
  jpa:
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
